grails-app/domain/com/student/Student.groovy
package com.student

import com.administration.School
import com.schedule.DesiredScheduleCriteria;
import com.schedule.Schedule;
import com.security.User;

class Student extends User{
	String firstName
	String lastName
	String email
	School school
	Schedule desiredSchedule
	DesiredScheduleCriteria desiredScheduleCriteria
	
	static mapping={
		version false
		friends joinTable:[name: 'STUDENT_FRIENDS']
		friendRequests joinTable:[name: 'STUDENT_FRIEND_REQUESTS']
		firstName defaultValue: ""
		lastName defaultValue:""
		assignedSchedules cascade:'all'	
	}
    static constraints = {
		firstName nullable:false
		lastName nullable:false
		email nullable:false,unique:true
		school nullable:true
		desiredSchedule nullable:true
		desiredScheduleCriteria nullable:true
    }
	static hasMany=[friends:Student,friendRequests:Student,assignedSchedules:Schedule]
}

grails-app/controllers/com/student/FriendsController.groovy
package com.student

class FriendsController {
	def springSecurityService
	
	/**
	 * Action to display a user's friends
	 *
	 * @return list of user's friend sort by last name then first name
	 */
	def myFriends() {
		log.info "myFriends entered"
		def friendList = []
		// Get current user from spring security service
		def user = (Student)springSecurityService.currentUser

		// Get user's friends sorted by last name then first name
		friendList = user.friends.sort{
			[it.lastName, it.firstName]
		}.reverse()
		log.info "friends list created"
		render view:'myFriends',model:[friends:friendList]
	}

	/**
	 * Action to unfriend a friend
	 * @param friend the student to unfriend
	 *
	 * @return redirect to friends list
	 */
	def unfriend(Student friend){
		log.info "unfriend entered"
		try{
			if (!friend)
				throw new Exception("Friend not found")

			// Get current user from spring security service
			def user = (Student)springSecurityService.currentUser

			// remove from each other's friends list
			user.removeFromFriends(friend)
			friend.removeFromFriends(user)

			// save changes to database
			user.save(flush:true)
			friend.save(flush:true)
			log.info "Unfriend successful"
			flash.message = "${friend.firstName} ${friend.lastName} removed from friends"
			redirect action:'myFriends'
		}
		catch(Exception e){
			log.info "Exception occurred"
			log.error e.stackTrace.toString()
			flash.error = e.getMessage()
			redirect action:'myFriends'
		}
	}

	def manageFriends(){
	}

	/**
	 * Ajax action to search for student's that match the name search query 
	 *
	 * @param name first and last name of the student requested
	 * @return list of search results that match the name
	 */
	def searchFriends(){
		log.info "unfriend entered"
		try{
			// Get current user from spring security service
			def user = (Student)springSecurityService.currentUser

			String query = params.name
			if(query?.split(" ")?.length<2) {
				log.info "First and last name not entered"
				render "First and last name must be entered"
				return
			}

			String fName = query?.split(" ")[0]?.trim()
			String lName = query?.substring(query.indexOf(' '))?.trim()

			def studentList = []
			def studentMap = [:]
			studentList = Student.findAllWhere(firstName:fName,lastName:lName,enabled:true)
			// Determine state to describe user's current relationship with other student s
			for(s in studentList){
				// Default relationship is stranger
				String state = "stranger"
				if(user.friendRequests.contains(s)) // User has a request from student s
					state="recieved"
				else if(s.friendRequests.contains(user)) // User sent a friend request to student s
					state="sent"
				else if(user.friends.contains(s)) // User is already friend with student s
					state="friend"
				studentMap.put(s,state)
			}
			log.info "Generated search result list"

			if(studentList.isEmpty()){
				log.info "No matching student found"
				render "No results"
			} else {
				log.info "Matching student(s) found"
				render (template:'/friends/friend_search_result_list',model:[result:studentMap])
			}
		}
		catch(Exception e){
			log.info "Exception occurred"
			log.error e.stackTrace.toString()
			render e.getMessage()
		}
	}

	/**
	 * Ajax action to send a friend request to another student
	 *
	 * @param s the student to send a friend request to
	 * @return error message if failed, otherwise "Friend request sent"
	 */
	def sendFriendRequest(Student s){
		log.info "sendFriendRequest"
		try{
			if(!s || !s.enabled)
				throw new Exception("Student could not be located")

			// Get current user
			def user = (Student)springSecurityService.currentUser
			if(s.friendRequests?.contains(user))
				throw new Exception("Friend request already sent");

			// Add current user to Student s's friend request list
			s.friendRequests.add(user)
			log.info "Current user added to student's friend request list"
			s.save(flush:true)
			render "Friend request sent";
		}
		catch(Exception e){
			log.info "Exception occurred"
			log.error e.stackTrace.toString()
			render e.getMessage()
		}
	}

	/**
	 * Ajax action to accept a friend request
	 *
	 * @param s the student whose friend request to accept
	 * @return error message if failed, otherwise "Friend request accepted"
	 */
	def acceptFriendRequest(Student s){
		log.info "acceptFriendRequest"
		try{
			if(!s || !s.enabled)
				throw new Exception("Student could not be located")

			// Get current user
			def user = (Student)springSecurityService.currentUser

			if(user.friends.contains(s)){
				// Student is already a friend. Remove friend request
				log.info "Student already is friend"
				user.friendRequests.remove(s)
				log.info "Friend request removed"
			} else {
				user.friends.add(s)
				log.info "Student added to friends"
				s.friends.add(user)
				log.info "User added to Student's friends"
				user.friendRequests.remove(s)
				log.info "Friend request removed"
			}
			render "Friend request accepted"
		}
		catch(Exception e){
			log.info "Exception occurred"
			log.error e.stackTrace.toString()
			render e.getMessage()
		}
	}

	/**
	 * Ajax action to decline a friend request
	 *
	 * @param s the student whose friend request to decline
	 * @return error message if failed, otherwise "Friend request declined"
	 */
	def declineFriendRequest(Student s){
		log.info "declineFriendRequest entered"
		try{
			if(!s || !s.enabled)
				throw new Exception("Student could not be located")

			// Get current user
			def user = (Student)springSecurityService.currentUser

			if(user.friends.contains(s)){
				// Student is already a friend. Remove friend request
				log.info "Student already is friend"
				user.friendRequests.remove(s)
				log.info "Friend request removed"
			} else {
				user.friendRequests.remove(s)
				log.info "Friend request declined and removed"
			}
			render "Friend request declined"
		}
		catch(Exception e){
			log.info "Exception occurred"
			log.error e.stackTrace.toString()
			render e.getMessage()
		}
	}

	/**
	 * Action to view the user's friend requests
	 *
	 * @return list of the user's friend requests
	 */
	def requests(){
		log.info "requests entered"
		try{
			// Get current user
			def user = (Student)springSecurityService.currentUser

			// Get user's friend requests sorted by last name, first name
			def requests=user.friendRequests.sort{
				[it.lastName, it.firstName]
			}.reverse()
			render view:'requests',model:[requests:requests]
		}
		catch(Exception e){
			log.info "Exception occurred"
			log.error e.stackTrace.toString()
			render e.getMessage()
		}
	}
}

grails-app/controllers/com/student/StudentController.groovy
package com.student

import static org.springframework.http.HttpStatus.*

import com.administration.School;

import grails.transaction.Transactional

@Transactional(readOnly = true)
class StudentController {
	def springSecurityService;
	static allowedMethods = [save: "POST", update: "PUT", delete: "DELETE"]

	/**
	 * Action to display a student's dashboard
	 *
	 * @return the student's dashboard
	 */
	def index() {
		render view:'index';
	}

	/**
	 * Action to display a student's account
	 *
	 * @return the student's account
	 */
	def myAccount(){
		log.info "myAccount entered"
		// Get current user
		def user = (Student)springSecurityService.currentUser
		render view:'myAccount',model:[student:user]
	}

	/**
	 * Action to update a student's account with the information passed in
	 *
	 * @param password (optional) the new password
	 * @param passwordConfirm (optional) the new password. must equal password
	 * @param email (optional) the new email
	 * @param firstName (optional) the new first name
	 * @param lastName (optional) the new last name
	 * @param school (optional) the new school
	 * @return the student's dashboard with any confirmation or error messages
	 */
	@Transactional
	def updateAccount(){
		log.info "updateAccount entered"
		try{
			// Get current user
			def user = (Student)springSecurityService.currentUser

			if(!params.password?.trim()?.isEmpty() || 
				!params.passwordConfirm?.trim()?.isEmpty()){
				user.password = params.password
				log.info "update password"
			}

			def errors = [];
			if(!user.email.equalsIgnoreCase(params.email?.trim())){
				String email = params.email?.trim()
				if(Student.findWhere(email:email))
					errors.add("Email is already associated with an account")
				else{
					user.email = email
					log.info "update email"
				}
			}

			String fName = params.firstName?.trim()
			if(fName.isEmpty())
				errors.add("First name must be entered")
			else {
				user.firstName = fName
				log.info "update first name"
			}
			
			String lName = params.lastName?.trim()
			if(lName.isEmpty())
				errors.add("Last name must be entered")
			else {
				user.lastName=lName
				log.info "update last name"
			}

			def s = params.school.id
			user.school = School.get(params.school.id as long)
			log.info "update school"

			if(!errors.isEmpty()){
				flash.errors=errors
				log.info "Validation errors: ${errors}"
				log.info "update invalid"
				render view:'myAccount',model:[student:user]
			} else {
				log.info "update successful"
				user.save(flush:true)
				log.info "save user to database"
				flash.message="Account updated"
				redirect action:'myAccount'
			}
		}
		catch(Exception e){
			log.info "Exception occurred"
			log.error e.stackTrace.toString()
			flash.error=e.getMessage()
			redirect action:'myAccount'
		}
	}
}

grails-app/views/student/_form.gsp
<%@ page import="com.student.Student" %>



<div class="fieldcontain">
	<label for="username">
		<g:message code="student.username.label" default="Username" />
	</label>
	<input class="form-control" value="${student?.username}" type="text" disabled>

</div>


<div class="fieldcontain ${hasErrors(bean: student, field: 'email', 'error')} required">
	<label for="email">
		<g:message code="student.email.label" default="Email" />
		<span class="required-indicator">*</span>
	</label>
	<g:textField name="email" required="" value="${student?.email}" class="form-control"/>

</div>

<div class="fieldcontain ${hasErrors(bean: student, field: 'password', 'error')}">
	<label for="password">
		<g:message code="student.password.label" default="Password" />
	</label>
	<g:textField name="password" class="form-control"/>
</div>

<div class="fieldcontain ${hasErrors(bean: student, field: 'password', 'error')}">
	<label for="passwordConfirm">
		<g:message code="student.password.label" default="Confirm Password" />
	</label>
	<g:textField name="passwordConfirm" class="form-control"/>
</div>

<div class="fieldcontain ${hasErrors(bean: student, field: 'firstName', 'error')} required">
	<label for="firstName">
		<g:message code="student.firstName.label" default="First Name" />
		<span class="required-indicator">*</span>
	</label>
	<g:textField name="firstName" required="" value="${student?.firstName}" class="form-control"/>

</div>

<div class="fieldcontain ${hasErrors(bean: student, field: 'lastName', 'error')} required">
	<label for="lastName">
		<g:message code="student.lastName.label" default="Last Name" />
		<span class="required-indicator">*</span>
	</label>
	<g:textField name="lastName" required="" value="${student?.lastName}" class="form-control"/>

</div>

<div class="fieldcontain ${hasErrors(bean: student, field: 'school', 'error')} required">
	<label for="school">
		<g:message code="student.school.label" default="School" />
		<span class="required-indicator">*</span>
	</label>
	<g:select id="school" name="school.id" from="${com.administration.School.list()}" optionKey="id" required="" value="${student?.school?.id}" class="many-to-one form-control"/>

</div>

grails-app/views/student/_student_sidebar.gsp
<g:each in="${itemMap}" var="item">
	<li>
		<g:link controller="${item.value[0]}" action="${item.value[1]}">${item.key}</g:link>
	</li>
</g:each>

grails-app/views/student/create.gsp
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'student.label', default: 'Student')}" />
		<title><g:message code="default.create.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#create-student" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="create-student" class="content scaffold-create" role="main">
			<h1><g:message code="default.create.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${studentInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${studentInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<g:form url="[resource:studentInstance, action:'save']" >
				<fieldset class="form">
					<g:render template="form"/>
				</fieldset>
				<fieldset class="buttons">
					<g:submitButton name="create" class="save" value="${message(code: 'default.button.create.label', default: 'Create')}" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

grails-app/views/student/index.gsp
<%@ page import="com.student.Student" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="student">
		<g:set var="entityName" value="${message(code: 'student.label', default: 'Student')}" />
		<title>Student Dashboard</title>
	</head>
	<body>
		<h2>Welcome, <g:currentName/></h2>
	</body>
</html>

grails-app/views/student/myAccount.gsp
<%@ page import="com.student.Student"%>
<!DOCTYPE html>
<html>
<head>
<meta name="layout" content="student">
<g:set var="entityName"
	value="${message(code: 'student.label', default: 'Student')}" />
<title>My Account</title>
</head>
<body>
	<div id="edit-student" class="content" role="main">
		<h1>My Account</h1>
		<g:if test="${flash.message}">
			<div class="alert alert-success" role="status">
				${flash.message}
			</div>
		</g:if>
		<g:if test="${flash.errors}">
			<div class="row">
				<br />
				<div class="alert alert-danger">
					<h3>Errors</h3>
					<ul>
						<g:each in="${flash.errors}" var="error">
							<li>
								${error}
							</li>
						</g:each>
					</ul>
				</div>
			</div>
		</g:if>
		<div class="row">
			<div class="col-md-5">
				<g:form url="[action:'updateAccount']" method="PUT">
					<fieldset class="form">
						<g:render template="form" />
					</fieldset>
					<fieldset class="buttons">
						<g:actionSubmit class="save" action="updateAccount"
							class="btn btn-primary"
							value="${message(code: 'default.button.update.label', default: 'Update')}" />
					</fieldset>
				</g:form>
			</div>
		</div>
	</div>
</body>
</html>