grails-app/domain/com/administration/Administrator.groovy
package com.administration

import com.security.User;

class Administrator extends User{

    static constraints = {
    }
	
	
}

grails-app/controllers/com/administration/AdministratorController.groovy
package com.administration

import static org.springframework.http.HttpStatus.*

import com.security.AccountRequest;
import com.security.SecRole;
import com.security.User
import com.security.UserSecRole;
import com.student.Student;

import grails.transaction.Transactional

@Transactional(readOnly = true)
class AdministratorController {

	static allowedMethods = [save: "POST", update: "PUT", delete: "DELETE"]
	def grailsApplication
	def studentService

	/**
	 * Action to generate and render the administrator dashboard
	 * @return
	 */
	def index() {
		log.info "index entered"

		def accountRequestCount = AccountRequest.count();//get the number of requests
		render view:'index', model:[accountRequestCount:accountRequestCount];
	}
	/**
	 * Action to show student account requests
	 * @return
	 */
	def requests(){
		log.info "requests entered"

		def sortOrder = ""
		if (params.order == "asc" || params.order == "desc")//check to user selected sort order
			sortOrder = params.order
		else
			sortOrder = "asc"

		// Using criteria instead of AccountRequest.list(sort: ..., order: ...)
		// is required because of some problems with GORM and nested properties
		def criteria = AccountRequest.createCriteria()
		def requests
		switch (params.sort) {//get list of requests sorted by sort column
			case "student.school.name":
				requests = criteria.list {
					student {
						school { order("name", sortOrder) }
					}
				}
				break;
			case "student.firstName":
				requests = criteria.list {
					student { order("firstName", sortOrder) }
				}
				break;
			case "student.lastName":
				requests = criteria.list {
					student { order("lastName", sortOrder) }
				}
				break;
			case "student.username":
				requests = criteria.list {
					student { order("username", sortOrder) }
				}
				break;
			case "student.email":
				requests = criteria.list {
					student { order("email", sortOrder) }
				}
				break;
			case "dateTime":
			default:
				requests = criteria.list { order("dateTime", sortOrder) }
		}

		def requestCount = AccountRequest.count()
		render view:'requests', model:[accountRequestInstanceList:requests,accountRequestInstanceCount:requestCount]
	}
	/**
	 * Action to reject an account request
	 * @param r the account request to reject
	 * @return
	 */
	@Transactional
	def rejectRequest(AccountRequest r){
		log.info "rejectRequest entered"

		try{
			if (!r)
				throw new Exception("Account request could not be located")
			def user = r.student//get request's user
			if (r.delete())//remove request from database
				log.info "Deleted request"
			if (user.delete())//remove user from database
				log.info "Deleted user"
			flash.message="Account request rejected"
			redirect action:'requests'
		}
		catch(Exception e){
			log.info "Exception occurred"
			log.error e.stackTrace.toString()
			flash.error = e.getMessage()
			redirect action:'requests'
		}
	}
	/**
	 * Action to approve account requests
	 * @param r the account request to approve
	 * @return
	 */
	@Transactional
	def approveRequest(AccountRequest r){
		log.info "approveRequest entered"

		try{
			approveAccountRequest(r)//approve request
			flash.message = "Account request approved"
			redirect action:'requests';
		}
		catch(Exception e){
			log.info "Exception occurred"
			log.error e.stackTrace.toString()
			flash.error = e.message
			redirect action:'requests'
		}
	}
	/**
	 * Action to approve all pending account requests
	 * @return
	 */
	@Transactional
	def approveAllRequests(){
		log.info "approveAllRequests entered"

		try{
			def requests=AccountRequest.findAll()//find all requests in database
			for (r in requests) {
				approveAccountRequest(r, true)
			}
			flash.message = "All account requests approved"
			redirect action:'requests';
		}
		catch(Exception e){
			log.info "Exception occurred"
			log.error e.stackTrace.toString()
			flash.error = e.message
			redirect action:'requests';
		}
	}

	/**
	 * Method to approve an account request
	 * @param r account request to approve
	 * @return
	 * @throws Exception
	 */
	private def approveAccountRequest(AccountRequest r, boolean flushImmediately = false) throws Exception{
		if (!r)
			throw new Exception("Account request could not be located")

		// Enable student
		Student s = r.student
		s.enabled = true
		s.save(flush:flushImmediately)

		// Add authentication for the student
		def studentRole = SecRole.findWhere(authority: 'ROLE_STUDENT')
		if (UserSecRole.create(s, studentRole, true))
			log.info "User account approved"

		// Delete request
		if (r.delete(flush:flushImmediately))
			log.info "Request removed"

		if (!grailsApplication.config.grails.mail.disabled)
			notifyByEmail(s.email, s.firstName, s.lastName)
	}

	/**
	 * Notify user by email of account approval
	 * @param email email address to send message to
	 * @param firstName user's first name
	 * @param lastName user's last name
	 * @return
	 */
	private def notifyByEmail(String email, String firstName, String lastName){
		sendMail {
			async true
			to email
			subject "HISP Account Approved"
			html """<h2>Welcome to HISP</h2>
				<p>${firstName} ${lastName}, your student account request at HISP has been approved.<p>
				<p>You can now login and enjoy everything our site has to offer!<p>"""
		}
	}
	/**
	 * Action to view all student accounts in the system
	 * @return
	 */
	def studentAccounts(){
		log.info "studentAccounts entered"

		def max = Math.min(params.max?.toInteger() ?: 10, 100)
		def offset = params.offset ? params.offset.toInteger() : 0
		def students = Student.findAllByEnabled(true, [offset: offset, max: max])

		render view:'studentAccounts', model:[studentInstanceList:students, studentInstanceCount: students.size()]
	}
	/**
	 * Action to delete a student account from the system.
	 * @param s the student account to be deleted
	 * @return
	 */
	@Transactional
	def deleteStudent(Student s){
		log.info "deleteStudent entered"

		try{
			studentService.deleteStudent(s)
			/*if(!s)
				throw new Exception("Student account could not be located")
			if(!s.enabled)
				throw new Exception("Student account not enabled")
			Collection<UserSecRole> roles = UserSecRole.findAllByUser((User)s);//find all security roles for student account
			roles*.delete(flush:true)
			for(f in s.friends)
				f.removeFromFriends(s)
			if (s.delete())//delete student account from database
				log.info "Student deleted"*/
			flash.message = "Student account deleted"
			redirect action:'studentAccounts'
		}
		catch(Exception e){
			log.info "Exception occurred"
			log.error e.stackTrace.toString()
			flash.error = e.message
			redirect action:'studentAccounts'
		}
	}
}

grails-app/views/administrator/_form.gsp
<%@ page import="com.administration.Administrator" %>



<div class="fieldcontain ${hasErrors(bean: administratorInstance, field: 'username', 'error')} required">
	<label for="username">
		<g:message code="administrator.username.label" default="Username" />
		<span class="required-indicator">*</span>
	</label>
	<g:textField name="username" required="" value="${administratorInstance?.username}"/>

</div>

<div class="fieldcontain ${hasErrors(bean: administratorInstance, field: 'password', 'error')} required">
	<label for="password">
		<g:message code="administrator.password.label" default="Password" />
		<span class="required-indicator">*</span>
	</label>
	<g:textField name="password" required="" value="${administratorInstance?.password}"/>

</div>

<div class="fieldcontain ${hasErrors(bean: administratorInstance, field: 'enabled', 'error')} ">
	<label for="enabled">
		<g:message code="administrator.enabled.label" default="Enabled" />
		
	</label>
	<g:checkBox name="enabled" value="${administratorInstance?.enabled}" />

</div>

grails-app/views/administrator/create.gsp
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'administrator.label', default: 'Administrator')}" />
		<title><g:message code="default.create.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#create-administrator" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="create-administrator" class="content scaffold-create" role="main">
			<h1><g:message code="default.create.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${administratorInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${administratorInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<g:form url="[resource:administratorInstance, action:'save']" >
				<fieldset class="form">
					<g:render template="form"/>
				</fieldset>
				<fieldset class="buttons">
					<g:submitButton name="create" class="save" value="${message(code: 'default.button.create.label', default: 'Create')}" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

grails-app/views/administrator/edit.gsp
<%@ page import="com.administration.Administrator" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'administrator.label', default: 'Administrator')}" />
		<title><g:message code="default.edit.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#edit-administrator" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="edit-administrator" class="content scaffold-edit" role="main">
			<h1><g:message code="default.edit.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${administratorInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${administratorInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<g:form url="[resource:administratorInstance, action:'update']" method="PUT" >
				<g:hiddenField name="version" value="${administratorInstance?.version}" />
				<fieldset class="form">
					<g:render template="form"/>
				</fieldset>
				<fieldset class="buttons">
					<g:actionSubmit class="save" action="update" value="${message(code: 'default.button.update.label', default: 'Update')}" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

grails-app/views/administrator/index.gsp
<%@ page import="com.administration.Administrator"%>
<!DOCTYPE html>
<html>
<head>
<meta name="layout" content="admin">
<g:set var="entityName"
	value="${message(code: 'administrator.label', default: 'Administrator')}" />
<title><g:message code="default.list.label" args="[entityName]" /></title>
</head>
<body>
	<h2>Administrator Dashboard</h2>
	<div>
		<h3>Account Requests: ${accountRequestCount}</h3>
	</div>
</body>
</html>

grails-app/views/administrator/requests.gsp
<%@ page import="com.security.AccountRequest"%>
<!DOCTYPE html>
<html>
<head>
<meta name="layout" content="admin">
<g:set var="entityName"
	value="${message(code: 'accountRequest.label', default: 'AccountRequest')}" />
<title><g:message code="default.list.label" args="[entityName]" /></title>
</head>
<body>
	<div id="list-accountRequest" class="content scaffold-list" role="main">
		<h1>Student Account Requests</h1>
		<g:if test="${flash.message}">
			<div class="alert alert-success" role="status">
				${flash.message}
			</div>
		</g:if>
		<g:if test="${flash.error}">
			<div class="alert alert-danger" role="status">
				${flash.error}
			</div>
		</g:if>
		<table class="table table-striped">
			<thead>
				<tr>
					<g:sortableColumn property="student.school.name"
						title="${message(code: 'accountRequest.student.school.name.label', default: 'School Name')}" />

					<g:sortableColumn property="student.firstName"
						title="${message(code: 'accountRequest.student.firstName.label', default: 'First Name')}" />

					<g:sortableColumn property="student.lastName"
						title="${message(code: 'accountRequest.student.lastName.label', default: 'Last Name')}" />


					<g:sortableColumn property="student.username"
						title="${message(code: 'accountRequest.student.username.label', default: 'Username')}" />

					<g:sortableColumn property="student.email"
						title="${message(code: 'accountRequest.student.email.label', default: 'Email')}" />

					<g:sortableColumn property="dateTime"
						title="${message(code: 'accountRequest.dateTime.label', default: 'Date')}" />
					<th>Actions</th>
				</tr>
			</thead>
			<tbody>
				<g:each in="${accountRequestInstanceList}" status="i"
					var="accountRequestInstance">
					<tr class="${(i % 2) == 0 ? 'even' : 'odd'}">
						<td>
							${fieldValue(bean: accountRequestInstance, field: "student.school.name")}
						</td>

						<td>
							${fieldValue(bean: accountRequestInstance, field: "student.firstName")}
						</td>

						<td>
							${fieldValue(bean: accountRequestInstance, field: "student.lastName")}
						</td>


						<td>
							${fieldValue(bean: accountRequestInstance, field: "student.username")}
						</td>

						<td>
							${fieldValue(bean: accountRequestInstance, field: "student.email")}
						</td>

						<td><g:formatDate date="${accountRequestInstance.dateTime}"
								format="MM/dd/yyyy hh:mm aa" /></td>

						<td><g:link controller="administrator"
								action="approveRequest" id="${accountRequestInstance.id}"
								class="btn btn-xs btn-success action-btn btn-icon"
								title="Approve request">
								<i class="fa fa-check fa-lg"></i>
							</g:link> <g:link controller="administrator" action="rejectRequest"
								id="${accountRequestInstance.id}"
								class="btn btn-xs btn-danger action-btn btn-icon"
								title="Reject request">
								<i class="fa fa-times fa-lg"></i>
							</g:link></td>
					</tr>
				</g:each>
			</tbody>
		</table>
		<div class="pagination">
			<g:paginate total="${accountRequestInstanceCount ?: 0}" />
		</div>
		<div>
			<g:link controller="administrator"
				action="approveAllRequests"
				class="btn btn-default btn-success action-btn"
				title="Approve all requests">
				<span>Approve All Requests</span>
			</g:link>
		</div>
	</div>
</body>
</html>

grails-app/views/administrator/show.gsp
<%@ page import="com.administration.Administrator" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'administrator.label', default: 'Administrator')}" />
		<title><g:message code="default.show.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#show-administrator" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="show-administrator" class="content scaffold-show" role="main">
			<h1><g:message code="default.show.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<ol class="property-list administrator">
			
				<g:if test="${administratorInstance?.username}">
				<li class="fieldcontain">
					<span id="username-label" class="property-label"><g:message code="administrator.username.label" default="Username" /></span>
					
						<span class="property-value" aria-labelledby="username-label"><g:fieldValue bean="${administratorInstance}" field="username"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${administratorInstance?.password}">
				<li class="fieldcontain">
					<span id="password-label" class="property-label"><g:message code="administrator.password.label" default="Password" /></span>
					
						<span class="property-value" aria-labelledby="password-label"><g:fieldValue bean="${administratorInstance}" field="password"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${administratorInstance?.enabled}">
				<li class="fieldcontain">
					<span id="enabled-label" class="property-label"><g:message code="administrator.enabled.label" default="Enabled" /></span>
					
						<span class="property-value" aria-labelledby="enabled-label"><g:formatBoolean boolean="${administratorInstance?.enabled}" /></span>
					
				</li>
				</g:if>
			
			</ol>
			<g:form url="[resource:administratorInstance, action:'delete']" method="DELETE">
				<fieldset class="buttons">
					<g:link class="edit" action="edit" resource="${administratorInstance}"><g:message code="default.button.edit.label" default="Edit" /></g:link>
					<g:actionSubmit class="delete" action="delete" value="${message(code: 'default.button.delete.label', default: 'Delete')}" onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

grails-app/views/administrator/studentAccounts.gsp
<%@ page import="com.student.Student"%>
<!DOCTYPE html>
<html>
<head>
<meta name="layout" content="admin">
<g:set var="entityName"
	value="${message(code: 'student.label', default: 'Student Account')}" />
<title><g:message code="default.list.label" args="[entityName]" /></title>
</head>
<body>
	<div id="list-student" class="content scaffold-list" role="main">
		<h1>
			<g:message code="default.list.label" args="[entityName]" />
		</h1>
		<g:if test="${flash.message}">
			<div class="alert alert-success" role="status">
				${flash.message}
			</div>
		</g:if>
		<g:if test="${flash.error}">
			<div class="alert alert-danger" role="status">
				${flash.error}
			</div>
		</g:if>
		<table class="table table-striped">
			<thead>
				<tr>

					<g:sortableColumn property="username"
						title="${message(code: 'student.username.label', default: 'Username')}" />

					<g:sortableColumn property="firstName"
						title="${message(code: 'student.firstName.label', default: 'First Name')}" />

					<g:sortableColumn property="lastName"
						title="${message(code: 'student.lastName.label', default: 'Last Name')}" />

					<g:sortableColumn property="email"
						title="${message(code: 'student.email.label', default: 'Email')}" />

					<th><g:message code="student.school.label" default="School" /></th>
					<th>Actions</th>
				</tr>
			</thead>
			<tbody>
				<g:each in="${studentInstanceList}" status="i" var="studentInstance">
					<tr class="${(i % 2) == 0 ? 'even' : 'odd'}">

						<td>${fieldValue(bean: studentInstance, field: "username")}</td>

						<td>
							${fieldValue(bean: studentInstance, field: "firstName")}
						</td>

						<td>
							${fieldValue(bean: studentInstance, field: "lastName")}
						</td>

						<td>
							${fieldValue(bean: studentInstance, field: "email")}
						</td>

						<td>
							${fieldValue(bean: studentInstance, field: "school")}
						</td>
						<td><g:link controller="administrator" action="deleteStudent"
								id="${studentInstance.id}" class="btn btn-xs btn-danger action-btn" title="Delete student">
								<i class="fa fa-trash-o fa-lg"></i>
							</g:link></td>
					</tr>
				</g:each>
			</tbody>
		</table>
		<div class="pagination">
			<g:paginate total="${studentInstanceCount ?: 0}" />
		</div>
	</div>
</body>
</html>