grails-app/domain/com/schedule/Course.groovy
package com.schedule

import com.administration.School;

class Course {
	String identity
	String title
    static constraints = {
		identity(unique: ['school'])
	}
	static mapping = {
		sections cascade:'all'
	}
	static hasMany = [sections:CourseSection]
	static belongsTo = [school:School]
	public String toString(){
		return "${identity}"
	}
}

grails-app/domain/com/schedule/CourseSection.groovy
package com.schedule

import com.administration.ScheduleBlock;
import com.student.Student;

class CourseSection {
	String teacher
	Integer semesterStart
	Integer semesterEnd
	static belongsTo=[block:ScheduleBlock,course:Course]
	static constraints = {
		block(unique: ['course', 'semesterStart', 'semesterEnd'])
		semesterStart validator:{val, obj -> val >= 1 && 
			val <= obj.block.schoolAcademicYear.school.numSemesters &&
			val <= obj.semesterEnd}
		semesterEnd validator:{val, obj -> val >= obj.semesterStart && val <= obj.block.schoolAcademicYear.school.numSemesters}
	}
	static mapping = {
	}
	public String toString(){
		return "${course.identity} - ${teacher} (${block})"
	}
}

grails-app/domain/com/schedule/DesiredScheduleCourse.groovy
package com.schedule

class DesiredScheduleCourse {
	Course course
	String teacher
	static belongsTo=[criteria:DesiredScheduleCriteria]
	static constraints = {
		course(unique: ['criteria'])
		teacher nullable:true
	}
}

grails-app/domain/com/schedule/DesiredScheduleCriteria.groovy
package com.schedule

import com.student.Student;

class DesiredScheduleCriteria {
	Integer year
	Integer semester
	String lunchDesiredDays
	static hasMany=[courses:DesiredScheduleCourse,excludedSections:CourseSection]
	static belongsTo=[student:Student]
    static constraints = {
    }
	static mapping={
		excludedSections joinTable:[name: 'DESIRED_SCHEDULE_CRITERIA_EXCLUDED_SECTIONS']
	}
}

grails-app/domain/com/schedule/Schedule.groovy
package com.schedule

import com.student.Student;

class Schedule {
	Integer year
	Integer semester
	Date lastUpdated
    static constraints = {
    }
    static mapping = {
    	courses cascade:'all'
    }
	static hasMany = [courses:CourseSection]
	static belongsTo = [student:Student]
}

grails-app/controllers/com/student/ScheduleController.groovy
package com.student

import com.schedule.CourseSection;
import com.schedule.DesiredScheduleCourse;
import com.schedule.DesiredScheduleCriteria
import com.schedule.DesiredScheduleFactory
import com.schedule.Schedule;
import com.schedule.Course;
import com.administration.ScheduleBlock;
import com.administration.AcademicYearScheduleBlockSet;
import com.administration.School;

import grails.transaction.Transactional
import static org.springframework.http.HttpStatus.*
import grails.converters.JSON

@Transactional(readOnly = true)
class ScheduleController {
	def springSecurityService;
	private static final MIN_YEAR=2013
	private static final COURSE_SEEN_THIS_YEAR = 1
	private static final COURSE_SEEN_PREV_YEAR = 0
	private static final COURSE_SEEN_NEVER = -1
	static allowedMethods = [save: "POST", update: "PUT", delete: "DELETE"]

	/**
	 * Method that sorts course sections by the following criteria:
	 * <p>
	 * <ul>
	 * <li> Compares periods
	 * <li> If the periods are the same, compare days
	 * <li> If the days are the same, compare course identities
	 * <ul>
	 * <p>
	 *
	 * @param sections the section to sort
	 * @return the sorted section
	 */
	private def sortSections(Object[] sections) {
		// Note: sections is Object[] because that is what groovy coerces .toArray() to
		log.info "Sorting course sections"
		return sections?.sort{ a,b ->
			a.block.periods <=> b.block.periods ?:
			a.block.days <=> b.block.days ?:
			a.course.identity <=> b.course.identity
		}
	}

	/**
	 * Action to view assigned schedule. If the user has an assigned schedule,
	 * the most recent one is shown by default
	 *
	 * @return the student's assigned schedule, listing the course sections
	 */
	def assigned() {
		log.info "assigned entered"
		def user = (Student)springSecurityService.currentUser

		// Preload some data for the form
		int currentYear = Calendar.getInstance().get(Calendar.YEAR)
		int maxYear = currentYear + 2
		int maxSemester = user.school.numSemesters
		int days = user.school.numDays
		int periods = user.school.numPeriods

		// Find out if the user has any schedules
		def assignedSchedules = user.assignedSchedules?.toArray()
		def scheduleExists = (assignedSchedules != null && assignedSchedules.length != 0)

		if (scheduleExists) {
			// If his schedule exists, show his most recent one
			def mostRecentSchedule = assignedSchedules[0]
			for (schedule in assignedSchedules) {
				if (schedule.year >= mostRecentSchedule.year &&
				schedule.semester > mostRecentSchedule.semester)
					mostRecentSchedule = schedule
			}

			def year = mostRecentSchedule.year
			def semester = mostRecentSchedule.semester
			log.info "showing most recent assigned schedule"
			render view:'assigned', model:[scheduleExists:true, schedule:mostRecentSchedule,
				year:year, semester:semester, minYear:MIN_YEAR,maxYear:maxYear,
				currentYear:currentYear, maxSemester:maxSemester, days:days,
				periods:periods]
		} else {
			// If his schedule doesn't exist, ask him to select a schedule
			render view:'assigned', model:[scheduleExists:false, minYear:MIN_YEAR,
				maxYear:maxYear, currentYear:currentYear, maxSemester:maxSemester,
				days:days, periods:periods]
		}
	}

	/**
	 * AJAX Action to view an assigned schedule.
	 * Displays the student's course, sorted by sortSections,
	 * with the ability to remove or add courses
	 *
	 * @return the student's assigned schedule, listing the course sections
	 */
	def getAssignedScheduleEditForm(int year, int semester, boolean showFriends) {
		log.info "getAssignedScheduleEditForm entered"
		try{
			def user = (Student)springSecurityService.currentUser
			def assignedSchedules = user.assignedSchedules.toArray()

			if (year < MIN_YEAR)
				throw new Exception("Invalid year $year")

			if (semester < 1 || semester > user.school.numSemesters)
				throw new Exception("Invalid semester $semester")

			log.info "Finding requested schedule"
			Schedule s = assignedSchedules.find{
				it.year == year && it.semester == semester && it.id != user.desiredSchedule?.id
			}
			if(!s){
				log.info "Schedule not found"
				s = new Schedule(year:year, semester:semester)
				user.addToAssignedSchedules(new Schedule(year:year, semester:semester))
				s.save()
				user.save()
			}

			def sections = s?.courses?.toArray()
			sections = sortSections(sections)

			def friendsInCourses = [:]
			if (showFriends) {
				log.info "Getting user's friends in the same school"
				def usersFriends = user?.friends?.toArray().findAll{
					it.school == user.school
				}

				log.info "Getting friends' schedules from the same semester"
				def friendsSchedulesList = usersFriends?.assignedSchedules?.flatten()
				def friendsSchedules = friendsSchedulesList?.toArray()?.findAll{
					it.year == year && it.semester == semester && it.student?.desiredSchedule?.id  != it.id
				}

				log.info "Mapping friends and courses"
				for (section in sections) {
					def friends = friendsSchedules?.findAll{
						section in it.courses
					}.collect{
						it.student
					}
					friendsInCourses[section] = friends.collect { it.firstName + " " + it.lastName}
				}
			}

			log.info "render form"
			render template:'/schedule/edit_assigned_schedule_form',model:[schedule:s, courses:sections,
				showFriends:showFriends, friends: friendsInCourses]
		}
		catch(Exception e){
			log.error "Exception occurred"
			log.error e.stackTrace.toString()
			response.status=500
			render e.getMessage()
		}
	}

	/**
	 * AJAX Action to remove a course from all assigned schedule.
	 *
	 * @return HTTP 500 if the course could not be removed, otherwise 200
	 */
	@Transactional
	def removeFromSchedule(long courseSectionId){
		log.info "removeFromSchedule entered"
		try{
			def user = (Student)springSecurityService.currentUser
			def section = CourseSection.get(courseSectionId)
			if (!section)
				throw new Exception("Course section $courseSectionId could not be found")

			log.info "Finding schedules"
			def schedules = user.assignedSchedules?.toArray()?.findAll{
				it.student.desiredSchedule?.id  != it.id && section in it.courses
			}
			for (schedule in schedules)
				removeCourseFromSchedule(schedule, section)
			render "Course removed"
		}
		catch(Exception e){
			log.error "Exception occurred"
			log.error e.stackTrace.toString()
			response.status = 500
			render e.getMessage()
		}
	}

	private def removeCourseFromSchedule(Schedule schedule, CourseSection section) throws Exception {
		log.info "removeCourseFromSchedule entered with schedule ${schedule?.id} and course ${section?.id}"

		if(!schedule?.courses?.contains(section)) {
			log.warn "Course ${section?.id} not found for schedule ${schedule?.id}"
			throw new Exception("Course section could not be removed")
		}

		log.info "Course ${section?.id} removed from schedule ${schedule?.id}"
		schedule.courses.remove(section)
		schedule.save(flush:true)
	}

	/**
	 * AJAX Action to validate if a course exists for a given year,
	 * courseId and the user's school.
	 * <p>
	 * The JSON object returned has the following properties:
	 * <ul>
	 * <li>courseTitle: title of the course (if it exists)
	 * <li>seenThisYear: if the courseId has been seen for this school this year
	 * <li>seenPrevYears: if the courseId has been seen for this school a prev year
	 * <ul>
	 * seenThisYear and seenPrevYears will never both be true
	 * <p>
	 *
	 * @param year the year (in YYYY format)
	 * @param courseId the (unique) string identifying the course for the school
	 * @return JSON object described above
	 */
	def validateCourse(int year, String courseId) {
		log.info "Validating course $courseId"
		try {
			if (year < MIN_YEAR)
				throw new Exception("Invalid year $year")

			def result = [:]

			def user = (Student)springSecurityService.currentUser
			def course = Course.findWhere(school:user.school, identity:courseId)

			def courseSeenStatus = courseSeen(year, course)

			result['courseTitle'] = course?.title
			result['seenThisYear'] = (courseSeenStatus == COURSE_SEEN_THIS_YEAR)
			result['seenPrevYears'] = (courseSeenStatus == COURSE_SEEN_PREV_YEAR)
			
			log.info "Returning course validation JSON"
			render result as JSON
		}
		catch(Exception e){
			log.error "Exception occurred"
			log.error e.stackTrace.toString()
			response.status = 500
			render e.getMessage()
		}
	}

	/**
	 * Private helper method to check when a course was most recently seen
	 *
	 * @param year the year (in YYYY format)
	 * @param course the course to search for
	 * @return the status of when a course was recently seen
	 */
	private def courseSeen(int year, Course course) {
		log.info "Checking if course $course was seen in the year $year"

		def sections = course?.sections?.toArray()
		def result = COURSE_SEEN_NEVER
		for (section in sections) {
			def sectionYear = section.block.schoolAcademicYear.year

			// Check if this section is recent
			if (sectionYear == year) {
				log.info "Course seen this year"
				return COURSE_SEEN_THIS_YEAR
			} else if (sectionYear < year) {
				log.info "Course seen in a previous year"
				result = COURSE_SEEN_PREV_YEAR
			}
		}

		return result
	}

	/**
	 * AJAX Action to update a course title.
	 * Note: this change is retroactive and will change titles of courses
	 * from previous years and semesters.
	 *
	 * @param year the year (in YYYY format)
	 * @param courseId the (unique) string identifying the course for the school
	 * @param courseTitle the new courseTitle. must be non-empty
	 * @return JSON with result true if the operation succeeded, false otherwise
	 */
	@Transactional
	def updateCourseTitle(int year, String courseId, String courseTitle) {
		log.info "Updating course '$courseId' with title '$courseTitle'"
		try {
			if (year < MIN_YEAR)
				throw new Exception("Invalid year $year")

			def user = (Student)springSecurityService.currentUser
			def course = Course.findWhere(school:user.school, identity:courseId)

			def result = [result:false]
			if (course == null) {

grails-app/views/schedule/_desired_courses_row.gsp
<div class="row course">
	<div class="col-md-5">
		<input name="desiredCourseIdentity" class="desiredCourseIdentityField" type="hidden" value="${desiredScheduleCourseInstance?.course?.identity }">
		${desiredScheduleCourseInstance?.course?.identity} - ${desiredScheduleCourseInstance?.course?.title}
	</div>
	<div class="col-md-5">
		<g:textField name="desiredCourseTeacher" class="form-control" placeholder="Teacher" value="${desiredScheduleCourseInstance?.teacher }" />
	</div>
	<div class="col-md-2">
		<a href="javascript:void(0);" class="btn btn-danger"
			onclick="removeCourse(this);"><i class="fa fa-minus"></i></a>
	</div>
</div>

grails-app/views/schedule/_desired_schedule_form.gsp
<div class="fieldcontain required">
	<label for="year"> Year <span class="required-indicator">*</span>
	</label>
	<g:textField name="year"
		value="${desiredScheduleCriteriaInstance?.year}" required=""
		class="form-control yearTextbox"/>
</div>
<div class="fieldcontain required">
	<label for="semester"> Semester <span
		class="required-indicator">*</span>
	</label>
	<g:textField name="semester"
		value="${desiredScheduleCriteriaInstance?.semester}" required=""
		class="form-control semesterTextbox"/>
</div>

<div class="fieldcontain">
	<label for="lunchDesiredDays"> Lunch Days
	</label>
	<g:textField name="lunchDesiredDays"
		value="${desiredScheduleCriteriaInstance?.lunchDesiredDays}" class="form-control lunchDaysTextbox" />
<script type="text/javascript">
	$(function() {
		$(".yearTextbox, .semesterTextbox").change(function(){
			var e=$(this)
			var excludedSections=$(".excludeCourseSection").length
			if(excludedSections>0||$("#excludeCourseSectionSelect").html().trim().length!=0){
				bootbox.confirm("Changing year or semester will clear excluded course sections. Continue?", function(result) {
					if(result){
					  	$(".excludeCourseSection").remove()
					  	$("#excludeCourseIdSearch").val("")
					  	$("#excludeCourseSectionSelect").html("")
					}
					 else
						$(e).val($(e).data('oldVal'))
				}); 
			}
		})
		$(".yearTextbox, .semesterTextbox").focus(function(){
			$(this).data('oldVal',$(this).val())
		})
	})
</script>
</div>
<hr>
<div class="fieldcontain">
	<label for="courses">Desired Courses </label>

	<div class="row">
		<div class="col-md-10">
			<g:textField name="addCourseSearchBox" id="addCourseSearchBox"
				class="form-control" placeholder="Course ID" />
		</div>
		<div class="col-md-2">
			<a href="javascript:void(0);" id="addCourseBtn" class="btn btn-success pull-right"><i
				class="fa fa-plus fa-lg"></i></a>
		</div>
	</div>
	<label for="courseFormContainer">Courses </label>
	<div id="courseFormContainer">
		<g:if test="${!desiredScheduleCriteriaInstance?.courses?.isEmpty()}">
			<g:each in="${desiredScheduleCriteriaInstance?.courses}" var="c">
				<g:render template="/schedule/desired_courses_row"
					model="[desiredScheduleCourseInstance:c]" />
			</g:each>
		</g:if>

	</div>
	<script type="text/javascript">
		$(function() {			
			$(window).keydown(function(event){
			    if(event.keyCode == 13) {
			      event.preventDefault();
			      return false;
			    }
			  });
			$("#addCourseBtn").click(function() {
				var query=$("#addCourseSearchBox").val().trim()
				var courseIds=$(".desiredCourseIdentityField")
				var exists=false
				for(i=0;i<courseIds.length;i++)
				{
					if($(courseIds[i]).val().toUpperCase()===query.toUpperCase()){
						exists=true
						break
					}
				}
				if(!exists){
					$.ajax({
					    url: "${createLink(controller:'schedule',action: 'addToDesiredCourses')}",
					    type: "GET",
					    data: {identity:query},
					    success: function(data, textStatus, xhr) {					    	
							$("#courseFormContainer").append(data)
							$("#addCourseSearchBox").val("")
					    },
					    error: function (jqXHR, textStatus,errorThrown){
							bootbox.alert(jqXHR.responseText);
						}
					})
				}
			});
		});
		function removeCourse(e) {
			$(e).closest(".course").remove();
		}
	</script>
</div>

<hr>
<div class="fieldcontain">
	<label for="excludedSections"> Excluded Course Sections </label>
	<div id="excludedSectionsFormContainer">
		<div>
			<div class="row">
				<div class="col-md-3">
					<g:textField name="excludeCourseIdSearch"
						id="excludeCourseIdSearch"
						class="form-control excludeCourseIdTextbox"
						placeholder="Course ID" />
				</div>
				<div class="col-md-7">
					<select id="excludeCourseSectionSelect" class="form-control"
						class="excludeCourseSectionSelect">
					</select>
				</div>
				<div class="col-md-2">
					<a href="javascript:void(0);" id="addExcludeCourseSectionBtn"
						class="pull-right btn btn-success"><i class="fa fa-plus fa-lg"></i></a>
				</div>
			</div>
		</div>
		<table class="table" id="excludedSectionsTable">
			<tr>
				<th>ID</th>
				<th>Teacher</th>
				<th>Period</th>
				<th>Days</th>
				<th>Semesters</th>
				<th></th>
			</tr>
			<g:if
				test="${!desiredScheduleCriteriaInstance?.excludedSections?.isEmpty()}">
				<g:each in="${desiredScheduleCriteriaInstance?.excludedSections}"
					var="c">
					<g:render template="/schedule/excluded_course_section_row"
						model="[section:c]" />
				</g:each>
			</g:if>
		</table>
	</div>
	<script type="text/javascript">
		$(function() {
			$("#excludeCourseIdSearch").bind("input",function(){
				var query=$(this).val()
				var year=$(".yearTextbox").val()
				var semester=$(".semesterTextbox").val()
				if(year.length>0&&semester.length>0){
					$.ajax({
					    url: "${createLink(controller:'schedule',action: 'searchByCourseIdentifier')}",
					    type: "GET",
					    data: {identity:query,year:year,semester:semester},
					    success: function(data, textStatus, xhr) {
						    $("#excludeCourseSectionSelect").html(data)
					    },
					    error: function (jqXHR, textStatus,errorThrown){
							bootbox.alert(jqXHR.responseText);
						}
					})
				}
			})
			$("#addExcludeCourseSectionBtn")
					.click(
							function() {
								var newExcludeId = $("#excludeCourseSectionSelect").val()
								if (newExcludeId!=null){
									var excludedIds=$(".excludedCourseId")
									var exists=false
									for(i=0;i<excludedIds.length;i++)
									{
										if($(excludedIds[i]).val()==newExcludeId){
											exists=true
											break
										}
									}
									if(!exists){
										$.ajax({
										    url: "${createLink(controller:'schedule',action: 'addToExcludedCourseSections')}",
													type : "GET",
													data : {
														id : newExcludeId
													},
													success : function(data,
															textStatus, xhr) {
														$('#excludedSectionsTable').append(data)
													},
													error : function(jqXHR,
															textStatus,
															errorThrown) {
														bootbox.alert(jqXHR.responseText);
													}
												})
									}
								}
							});
		});
		function removeExcludeCourseSection(e) {
			$(e).closest(".excludeCourseSection").remove();
		}
	</script>
</div>
<hr>

grails-app/views/schedule/_edit_assigned_schedule_form.gsp
<div id="schedule">
	<table class="table">
		<tr>
			<th>Period</th>
			<th>Days</th>
			<th>Course</th>
			<th>Teacher</th>
			<g:if test="${showFriends}"><th>Friends</th></g:if>
			<th>Action</th>
		</tr>
		<g:each in="${courses}" var="c">
			<tr id="${c.id}">
				<td>
					${c.block.periods}
				</td>
				<td>
					${c.block.days}
				</td>
				<td>
					${c.course.identity} - ${c.course.title}
				</td>
				<td>
					${c.teacher}
				</td>
				<g:if test="${showFriends}">
				<td>
					${friends[c]?.join(', ')}
				</td>
				</g:if>
				<td><div class="actionGroup">
						<button class="removeCourseBtn confirmButton btn btn-danger" courseSectionId="${c.id}">
							<i class="fa fa-trash-o fa-lg"></i>
						</button>
					</div></td>
			</tr>
		</g:each>
	</table>
	<script type="text/javascript">
	$(".removeCourseBtn").click(function(){
		var btn=$(this);
		bootbox.confirm("Delete course?",function(result){
			if (!result)
				return;
			$.ajax({
			    url: "${createLink(controller:'schedule',action: 'removeFromSchedule')}",
			    type: "POST",
			    data: {courseSectionId:$(btn).attr('courseSectionId')},
			    success: function(data, textStatus, xhr) {
				    $(btn).closest("tr").remove();
				    bootbox.alert("Course removed")
			    },
			    error: function (jqXHR, textStatus,errorThrown){
					bootbox.alert(jqXHR.responseText);
				}
			})
		})
	});
	</script>
</div>

grails-app/views/schedule/_excluded_course_section_row.gsp
<tr class="excludeCourseSection">
	<td><input type="hidden" value="${section.id}"
		name="excludedCourseIds" class="excludedCourseId"> ${section.course.identity}
	</td>
	<td>
		${section.teacher}
	</td>
	<td>
		${section.block.periods}
	</td>
	<td>
		${section.block.days}
	</td>
	<td>
		<% if(section.semesterStart == section.semesterEnd) {%>
		<%=section.semesterStart%>
		<%} else {%>
		<%="${section.semesterStart} - ${section.semesterEnd}"%>
		<% } %>
	</td>
	<td><a href="javascript:void(0);" class="btn btn-danger"
		onclick="removeExcludeCourseSection(this);"><i class="fa fa-minus"></i></a>
	</td>
</tr>

grails-app/views/schedule/_readonly_schedule.gsp
<div id="schedule">
	<table class="table">
		<tr>
			<th>Period</th>
			<th>Days</th>
			<th>Course</th>
			<th>Teacher</th>
		</tr>
		<g:each in="${sections}" var="c">
			<tr>
				<td>
					${c.block.periods}
				</td>
				<td>
					${c.block.days}
				</td>
				<td>
					${c.course.identity} - ${c.course.title}
				</td>
				<td>
					${c.teacher}
				</td>
			</tr>
		</g:each>
	</table>
</div>

grails-app/views/schedule/assigned.gsp
<!DOCTYPE html>
<html>
<head>
<meta name="layout" content="student">
<g:set var="entityName"
	value="${message(code: 'school.label', default: 'My Assigned Schedule')}" />
<title><g:message code="default.list.label" args="[entityName]" /></title>
<script type="text/javascript">
var hispUrls = {
	validationLink: "${createLink(controller:'schedule', action:
			'validateCourse')}",
	updateCourseTitleLink: "${createLink(controller:'schedule',action: 'updateCourseTitle')}",
	validateScheduleBlockLink: "${createLink(controller:'schedule',action: 'validateScheduleBlock')}",
	updateTeacherLink: "${createLink(controller:'schedule',action: 'updateTeacher')}",
	addCourseLink: "${createLink(controller:'schedule',action: 'addCourseToAssigned')}",
	getScheduleLink: "${createLink(controller:'schedule',action: 'getAssignedScheduleEditForm')}"
};
var hisp = hispUrls;

$(function(){
	$("#findScheduleButton").click(getSchedule);
	$("#showHideFriends").click(getSchedule);

	$("#addCourseBtn").click(function() {
		if (!$.isEmptyObject(hisp))
			hisp = hispUrls;
		$("#hidden #periodField").prop('multiple', true);
		$("#hidden #dayField").prop('multiple', true);
		showCourseIdDialog();
	});

	%{-- auto-load the schedule if schedule exists --}%
	<g:if test="${scheduleExists}">
	getSchedule();
	</g:if>
});
</script>
</head>
<body>
<h2>My Assigned Schedule</h2>
<g:if test="${flash.message}">
	<div class="alert alert-success" role="status">
		${flash.message}
	</div>
</g:if>
<g:if test="${flash.error}">
	<div class="alert alert-danger" role="status">
		${flash.error}
	</div>
</g:if>
<div id="scheduleSelector" class="row">
	<div class="col-md-12">
		<label>Year</label>
		<g:if test="${scheduleExists}">
			<g:select id="year" name="year" from="${minYear..maxYear}"
			value="${year}" />
		</g:if>
		<g:else>
			<g:select id="year" name="year" from="${minYear..maxYear}"
			value="${currentYear}" />
		</g:else>
		<label>Semester</label>
		<g:if test="${scheduleExists}">
			<g:select id="semester" name="semester" from="${1..maxSemester}"
			value="${semester}" />
		</g:if>
		<g:else>
			<g:select id="semester" name="semester" from="${1..maxSemester}" />
		</g:else>
		<button id="findScheduleButton" name="findScheduleButton" class="btn btn-primary">Get Schedule</button>
		<br>
		<label for="showHideFriends">Show Friends Schedules?</label>
		<input type="checkbox" id="showHideFriends">
	</div>
</div>	
<div class="row">
	<div class="col-md-12">
		<button id="addCourseBtn" class="btn btn-success pull-right" style="display: none;">Add Course</button>
	</div>
</div>
<div id="scheduleContainer" style="margin-top: 20px"></div>
<span id="hidden" style="display:none">
	<div class="form-group">
		<label for='periodField'>Period(s)</label>
		<g:select name="periodField" class="form-control" id="periodField" from="${1..periods}"/>
	</div>
	<div class="form-group">
		<label for='dayField'>Day(s)</label>
		<g:select name="dayField" class="form-control" id="dayField" from="${1..days}"/>
	</div>
	<div class="form-group">
		<label for='semStartField'>Semester Start</label>
		<input type="number" class="form-control" name="semStartField" id="semStartField" min="1" value="${semester}">
	</div>
	<div class="form-group">
		<label for='semEndField'>Semester End</label>
		<input type="number" class="form-control" id="semEndField" name="semEndField" min="1" value="${semester}">
	</div>
</span>
<asset:javascript src="scheduleAjax.js"/>
</body>
</html>

grails-app/views/schedule/createDesiredSchedule.gsp
<!DOCTYPE html>
<html>
<head>
<meta name="layout" content="student">
<g:set var="entityName"
	value="${message(code: 'schedule.label', default: 'Generate Desired Schedule')}" />
<title><g:message code="default.create.label"
		args="[entityName]" /></title>
</head>
<body>
	<div class="row">
		<div class="col-md-12">
			<div id="create-desired-schedule" class="content scaffold-create" role="main">
				<h1>
					<g:message code="default.create.label" args="[entityName]" />
				</h1>
				<g:if test="${flash.message}">
					<div class="alert alert-success" role="status">
						${flash.message}
					</div>
				</g:if>
				<div class="row">
					<div class="col-md-7">
						<g:form url="[action:'generateDesired']">
							<fieldset class="form">
								<g:render template="desired_schedule_form" />
							</fieldset>
							<fieldset class="buttons">
								<g:submitButton name="create" class="btn btn-primary"
									value="Generate" />
							</fieldset>
						</g:form>
					</div>
					<div class="col-md-7">
						<g:if test="${flash.errors||flash.error}">
							<div class="row">
								<br />
								<div class="alert alert-danger">
									<h4>Errors</h4>
									<g:if test="${flash.error }">
										${flash.error}
									</g:if>
									<g:else>
										<ul>
											<g:each in="${flash.errors}" var="error">
												<li>
													${error}
												</li>
											</g:each>
										</ul>
									</g:else>
								</div>
							</div>
						</g:if>
					</div>
				</div>
			</div>
		</div>
	</div>
</body>
</html>