grails-app/domain/com/administration/AcademicYearScheduleBlockSet.groovy
package com.administration

class AcademicYearScheduleBlockSet {
	Integer year
	static belongsTo=[school:School]
	static hasMany=[scheduleBlocks:ScheduleBlock]
    static constraints = {
		year(unique: ['school'])
    }
	static mapping={
		scheduleBlocks sort:'periods', cascade:'all'
	}
	public String getScheduleBlocksString(){
		StringBuilder sb=new StringBuilder()
		for(s in scheduleBlocks){
			sb.append("<${s.periods};${s.days}>")
		}
		return sb.toString()
	} 
}

grails-app/domain/com/administration/School.groovy
package com.administration

import com.schedule.Course;

class School {
	String name
	Integer numSemesters
	Integer numDays
	Integer numPeriods
	Integer lunchPeriodStart
	Integer lunchPeriodEnd
	
    static constraints = {
		name nullable:false, unique:true
		numSemesters nullable:false, range:1..4
		numDays nullable:false, range:1..7
		numPeriods nullable:false, range:1..12
		lunchPeriodStart nullable:false, validator:{val, obj -> val >= 1 && val <= obj.lunchPeriodStart}
		lunchPeriodEnd nullable:false, validator:{val, obj -> val >= obj.lunchPeriodEnd && val <= obj.numPeriods}
    }
	static mapping={
		academicYearSchedules sort:'year',cascade:'all'
		courses cascade:'all'
	}
	static hasMany=[academicYearSchedules:AcademicYearScheduleBlockSet,courses:Course]
	public String toString(){
		return name;
	}
}

grails-app/controllers/com/administration/SchoolController.groovy
package com.administration

import static org.springframework.http.HttpStatus.*

import com.schedule.Schedule;
import com.student.Student;

import grails.transaction.Transactional

@Transactional(readOnly = true)
class SchoolController {

	static allowedMethods = [save: "POST", update: "PUT"]

	def index(Integer max) {
		log.info "index Entered";
		params.max = Math.min(max ?: 10, 100)
		if(params.sort == null){
			params.sort = "name"
			params.order = "asc"
		}
		respond School.list(params), model:[schoolInstanceCount: School.count()]
	}

	def show(School schoolInstance) {
		respond schoolInstance
	}

	def create() {
		respond new School(params)
	}

	/**
	 * Action to save the add school form to database
	 * @return
	 */
	@Transactional
	def save() {
		log.info "save entered"
		School school
		try{
			def errors = []
			school = new School()
			//Get request parameters
			String name = params.name?.trim()
			String numSemesters = params.numSemesters?.trim()
			String numDays = params.numDays?.trim()
			String numPeriods = params.numPeriods?.trim()
			String lunchPeriodStart = params.lunchPeriodStart?.trim()
			String lunchPeriodEnd = params.lunchPeriodEnd?.trim()
			def years = params.list('years')
			def blocks = params.list('scheduleBlocks')
			//validate inputs
			if(name.isEmpty())
				errors.add("Name must be entered")
			if(School.findWhere(name:name))
				errors.add("School exists with name: ${name}")
			school.name = name
			if(numSemesters.isEmpty())
				errors.add("Semesters must be entered")
			school.numSemesters = Integer.parseInt(numSemesters)
			if(numDays.isEmpty())
				errors.add("Days must be entered")
			school.numDays = Integer.parseInt(numDays)
			if(numPeriods.isEmpty())
				errors.add("Periods must be entered")
			school.numPeriods = Integer.parseInt(numPeriods)
			if(lunchPeriodStart.isEmpty())
				errors.add("Lunch period start must be entered")
			school.lunchPeriodStart = Integer.parseInt(lunchPeriodStart)
			if(lunchPeriodEnd.isEmpty())
				errors.add("Lunch period end must be entered")
			school.lunchPeriodEnd = Integer.parseInt(lunchPeriodEnd)
			//validate school period logic
			if(school.lunchPeriodEnd > school.numPeriods)
				errors.add("Lunch period end cannot be greater than periods")
			if(school.lunchPeriodStart > school.numPeriods)
				errors.add("Lunch period start cannot be greater than periods")
			if(school.lunchPeriodEnd < school.lunchPeriodStart)
				errors.add("Lunch period start cannot be greater than lunch period end")

			if(blocks?.isEmpty())//check if school block has been entered
				errors.add("A year of schedule blocks must be entered")
			else{
				try{
					for(int i = 0; i < years.size(); i++){//loop over each academic year entered
						String year = years[i]?.trim()
						if(!year.isEmpty()){
							AcademicYearScheduleBlockSet yearBlocks = new AcademicYearScheduleBlockSet(year:(year as int), school:school)
							def blockList = ScheduleBlock.parseScheduleBlockString(blocks[i])//parse schedule block string into list of ScheduleBlocks
							log.info "parsing schedule block"
							for(b in blockList){//add blocks to school
								log.info "validating schedule block"
								if(school.numPeriods < (b.periods as int)){
									log.info "Invalid period in schedule block found ${b}"
									throw new Exception()
								}
								for(d in b.days.split(",")){
									if(school.numDays < (d as int))
									{
										log.info "Invalid days in schedule block found ${b}"
										throw new Exception()
									}
								}
								yearBlocks.addToScheduleBlocks(b)
							}
							school.addToAcademicYearSchedules(yearBlocks)
							log.info "academic year added"
						}
					}
					log.info "finished added schedule blocks"
				}
				catch(Exception e){
					errors.add("Invalid schedule block(s)")
				}
			}
			if (!errors.isEmpty()) {//check if validation errors have occurred
				log.info "validation errors occurred"
				flash.errors = errors
				render view:'create',model:[schoolInstance:school]
				return
			}
			school.save(flush:true)//save school
			log.info "school saved"
			redirect action:'index'
		}
		catch(Exception e){
			log.info "Exception occurred"
			log.error e.stackTrace.toString()
			flash.error = e.getMessage()
			render view:'create',model:[schoolInstance:school]
		}
	}

	def edit(School schoolInstance) {
		log.info "edit entered"
		render view:"edit",model:[schoolInstance:schoolInstance]
	}

	/**
	 * Action to handle updating a school's information
	 * @param schoolInstance the school to update
	 * @return
	 */
	@Transactional
	def update(School schoolInstance) {
		log.info "update entered"
		try{
			if (schoolInstance == null)
				throw new Exception("Could not locate school")
			def years = params.list('years')
			def scheduleBlocks = params.list('scheduleBlocks')
			log.info "retrieve academic year parameters"
			def currentYears=schoolInstance.academicYearSchedules
			def currentYearsMap=[:]
			for(y in currentYears)
				currentYearsMap.put(y.year,y)
				log.info "looping over all years submitted"
			for(int i = 0; i < years.size(); i++){
				String yearString = years[i].trim()
				if(!yearString.isEmpty()){
					int year=yearString as int
					log.info "parsing schedule block string"
					def blockSet = ScheduleBlock.parseScheduleBlockString(scheduleBlocks[i])
					AcademicYearScheduleBlockSet academicYear
					if(currentYearsMap.containsKey(year)){
						log.info "academic year already exists for school"
						academicYear=currentYearsMap.get(year)
						currentYearsMap.remove(year)
						def currentScheduleBlocks=[:]
						for(b in academicYear.scheduleBlocks.toArray())//create map to see if block has been deleted
							currentScheduleBlocks.put(b, false)
						for(b in blockSet){
							b.schoolAcademicYear=academicYear
							boolean exists=false
							for(c in currentScheduleBlocks){
								if(c.key.equals(b)){//check if schedule block already exists
									log.info "schedule block ${b} already exists"
									exists=true
									c.value=true
									break
								}
							}
							if(!exists){
								log.info "schedule block ${b} added to academic year"
								academicYear.addToScheduleBlocks(b)
							}
						}
						log.info "removing old schedule blocks"
						for(b in currentScheduleBlocks){
							if(!b.value){
								//remove course sections
								def schedules=Schedule.createCriteria().list {
									and{
										courses{
											eq('block',b.key)
										}
									}
								}
								log.info "removing course sections from schedules"
								for(s in schedules){
									for(cs in b.key.courseSections)
										s.removeFromCourses(cs)
									s.save(flush:true)
								}
								log.info "removing schedule block from academic year"
								academicYear.removeFromScheduleBlocks(b.key)
								b.key.delete(flush:true)
								log.info "schedule block removed"
							}
						}
					}
					else{
						log.info "academic year does not exist for school"
						academicYear = new AcademicYearScheduleBlockSet(school:schoolInstance, year:year)
						log.info "add schedule blocks to new academic year"
						for(b in blockSet){
							academicYear.addToScheduleBlocks(b)
						}
						schoolInstance.addToAcademicYearSchedules(academicYear)
						log.info "academic year added to school"
					}
				}
			}
			log.info "removing old academic years from school"
			for(y in currentYearsMap){//remove years no longer used in school
				def schedules=Schedule.createCriteria().list {
					and{
						eq('year',y.value.year)
						student{
							eq('school',schoolInstance)
						}
					}
				}
				log.info "removing all schedules in the academic year"
				for(s in schedules){
					s.courses.clear()
					s.delete(flush:true)
				}				
				schoolInstance.removeFromAcademicYearSchedules(y.value)
				y.value.delete(flush:true)
				log.info "academic year removed from school"
			}
			schoolInstance.save(flush:true)
			log.info "school update complete"
			flash.message="${schoolInstance.name} updated"
			redirect action:'edit',id:schoolInstance.id
		}
		catch(Exception e){
			log.info "Exception occurred"
			log.error e.stackTrace.toString()
			flash.error = e.getMessage()
			redirect action:'index'
		}
	}

	/**
	 * Action to delete a school from system
	 * @param schoolInstance the school to delete
	 * @return
	 */
	@Transactional
	def delete(School schoolInstance) {
		log.info "delete entered"
		def students = Student.findAllWhere(school:schoolInstance)
		for(s in students){//remove each student from school and remove schedule containing courses from database
			def assignedSchedules = s.assignedSchedules.toArray()
			for(sch in assignedSchedules){
				sch.courses.clear()
				sch.save(flush:true)
				s.removeFromAssignedSchedules(sch)
				sch.delete(flush:true)
			}
			s.assignedSchedules = null
			s.desiredSchedule = null
			s.school = null
			s.save(flush:true)
		}
		log.info "remove students from school and schedules"
		if (schoolInstance == null) {
			notFound()
			return
		}

		schoolInstance.delete flush:true
		log.info "school deleted"

		redirect action:'index'
	}

	protected void notFound() {
		request.withFormat {
			form multipartForm {
				flash.message = message(code: 'default.not.found.message', args: [
					message(code: 'school.label', default: 'School'),
					params.id
				])
				redirect action: "index", method: "GET"
			}
			'*'{ render status: NOT_FOUND }
		}
	}
}

grails-app/views/school/_form.gsp
<%@ page import="com.administration.School"%>

<div
	class="fieldcontain ${hasErrors(bean: schoolInstance, field: 'name', 'error')} required">
	<label for="numSemesters"> <g:message code="school.name.label"
			default="Name" /> <span class="required-indicator">*</span>
	</label>
	<g:textField name="name" value="${schoolInstance.name}" required=""
		class="form-control" />

</div>

<div
	class="fieldcontain ${hasErrors(bean: schoolInstance, field: 'numSemesters', 'error')} required">
	<label for="numSemesters"> <g:message
			code="school.numSemesters.label" default="Semesters" /> <span
		class="required-indicator">*</span>
	</label>
	<g:textField name="numSemesters" value="${schoolInstance.numSemesters}"
		required="" class="form-control" />

</div>

<div
	class="fieldcontain ${hasErrors(bean: schoolInstance, field: 'numDays', 'error')} required">
	<label for="numDays"> <g:message code="school.numDays.label"
			default="Days" /> <span class="required-indicator">*</span>
	</label>
	<g:textField name="numDays" value="${schoolInstance.numDays}"
		required="" class="form-control" />

</div>

<div
	class="fieldcontain ${hasErrors(bean: schoolInstance, field: 'numPeriods', 'error')} required">
	<label for="numPeriods"> <g:message
			code="school.numPeriods.label" default="Periods" /> <span
		class="required-indicator">*</span>
	</label>
	<g:textField name="numPeriods" value="${schoolInstance.numPeriods}"
		required="" class="form-control" />

</div>

<div
	class="fieldcontain ${hasErrors(bean: schoolInstance, field: 'lunchPeriodStart', 'error')} required">
	<label for="lunchPeriodStart"> <g:message
			code="school.lunchPeriodStart.label" default="Lunch Period Start" />
		<span class="required-indicator">*</span>
	</label>
	<g:textField name="lunchPeriodStart"
		value="${schoolInstance.lunchPeriodStart}" required=""
		class="form-control" />

</div>

<div
	class="fieldcontain ${hasErrors(bean: schoolInstance, field: 'lunchPeriodEnd', 'error')} required">
	<label for="lunchPeriodEnd"> <g:message
			code="school.lunchPeriodEnd.label" default="Lunch Period End" /> <span
		class="required-indicator">*</span>
	</label>
	<g:textField name="lunchPeriodEnd"
		value="${schoolInstance.lunchPeriodEnd}" required=""
		class="form-control" />

</div>

<div
	class="fieldcontain ${hasErrors(bean: schoolInstance, field: 'scheduleBlocks', 'error')} ">
	<label for="scheduleBlocks"> <g:message
			code="school.scheduleBlocks.label" default="Schedule Blocks ex:" />&lt;period;days&gt;

	</label>
	<div id="scheduleBlockFormContainer">
		<g:if test="${!schoolInstance.academicYearSchedules?.isEmpty()}">
			<g:each in="${schoolInstance.academicYearSchedules}" var="y">
				<div>
					<div class="row scheduleBlock">
						<div class="col-md-3">
							<g:textField name="years" class="form-control"
								placeholder="Year" value="${y.year }" />
						</div>
						<div class="col-md-7">
							<g:textArea name="scheduleBlocks" class="form-control"
								placeholder="Schedule Blocks" value="${y.scheduleBlocksString }" />
						</div>
						<div class="col-md-2">
							<a href="javascript:void(0);" class="btn btn-danger"
								onclick="removeYear(this);"><i class="fa fa-minus"></i></a>
						</div>
					</div>
				</div>
			</g:each>
		</g:if>
		<div class="scheduleBlockRow" style="display: none;">
			<div class="row scheduleBlock">
				<div class="col-md-3">
					<g:textField name="years" class="form-control"
						placeholder="Year" />
				</div>
				<div class="col-md-7">
					<g:textArea name="scheduleBlocks" class="form-control"
						placeholder="Schedule Blocks" />
				</div>
				<div class="col-md-2">
					<a href="javascript:void(0);" class="btn btn-danger removeYearBtn"
						onclick="removeYear(this);"><i class="fa fa-minus"></i></a>
				</div>
			</div>
		</div>
	</div>
	<div class="row">
		<div class="col-md-12">
			<a href="javascript:void(0);" id="addYearBtn" class="pull-right"><i
				class="fa fa-plus fa-lg"></i> Add Academic Year</a>
		</div>
	</div>
	<script type="text/javascript">
		$(function() {
			$("#addYearBtn").click(
					function() {
						$("#scheduleBlockFormContainer").append($(".scheduleBlockRow").html())
					});
		});
		function removeYear(e) {
			if ($(".scheduleBlock").length > 1)
				$(e).closest(".scheduleBlock").remove();
		}
	</script>
</div>

grails-app/views/school/create.gsp
<!DOCTYPE html>
<html>
<head>
<meta name="layout" content="admin">
<g:set var="entityName"
	value="${message(code: 'school.label', default: 'School')}" />
<title><g:message code="default.create.label"
		args="[entityName]" /></title>
</head>
<body>
	<div class="row">
		<div class="col-md-12">
			<div id="create-school" class="content scaffold-create" role="main">
				<h1>
					<g:message code="default.create.label" args="[entityName]" />
				</h1>
				<g:if test="${flash.message}">
					<div class="alert alert-success" role="status">
						${flash.message}
					</div>
				</g:if>
				<div class="row">
					<div class="col-md-7">
						<g:form url="[action:'save']">
							<fieldset class="form">
								<g:render template="form" />
							</fieldset>
							<fieldset class="buttons">
								<g:submitButton name="create" class="btn btn-primary"
									value="${message(code: 'default.button.create.label', default: 'Create')}" />
							</fieldset>
						</g:form>
					</div>
					<div class="col-md-7">
						<g:if test="${flash.errors||flash.error}">
							<div class="row">
								<br />
								<div class="alert alert-danger">
									<h3>Errors</h3>
									<g:if test="${flash.error }">
										${flash.error}
									</g:if>
									<g:else>
										<ul>
											<g:each in="${flash.errors}" var="error">
												<li>
													${error}
												</li>
											</g:each>
										</ul>
									</g:else>
								</div>
							</div>
						</g:if>
					</div>
				</div>
			</div>
		</div>
	</div>
</body>
</html>

grails-app/views/school/edit.gsp
<%@ page import="com.administration.School"%>
<!DOCTYPE html>
<html>
<head>
<meta name="layout" content="admin">
<g:set var="entityName"
	value="${message(code: 'school.label', default: 'School')}" />
<title><g:message code="default.edit.label" args="[entityName]" /></title>
</head>
<body>
	<div id="edit-school" class="content scaffold-edit" role="main">
		<h1>
			<g:message code="default.edit.label" args="[entityName]" />
		</h1>
		<g:if test="${flash.message}">
			<div class="alert alert-success" role="status">
				${flash.message}
			</div>
		</g:if>
		<g:if test="${flash.error}">
			<div class="alert alert-danger" role="status">
				${flash.error}
			</div>
		</g:if>
		<g:form url="[action:'update']" method="PUT">
			<g:hiddenField name="version" value="${schoolInstance?.version}" />
			<g:hiddenField name="id" value="${schoolInstance.id}" />
			<fieldset class="form">
				<g:render template="form" />
			</fieldset>
			<fieldset class="buttons">
				<g:actionSubmit class="save" action="update"
					value="${message(code: 'default.button.update.label', default: 'Update')}"
					class="btn btn-primary" />
			</fieldset>
		</g:form>
	</div>
</body>
</html>

grails-app/views/school/index.gsp
<%@ page import="com.administration.School"%>
<!DOCTYPE html>
<html>
<head>
<meta name="layout" content="admin">
<g:set var="entityName"
	value="${message(code: 'school.label', default: 'School')}" />
<title>Schools</title>
</head>
<body>
	<h1>Schools</h1>
	<div class="row">
		<div class="col-md-12">
			<g:link controller="school" action="create"
				class="btn btn-primary pull-right">Add School</g:link>
		</div>
		<div class="col-md-12">
			<g:if test="${flash.message}">
				<div class="alert alert-success" role="status">
					${flash.message}
				</div>
			</g:if>
			<g:if test="${flash.error}">
				<div class="alert alert-danger" role="status">
					${flash.error}
				</div>
			</g:if>
			<table class="table table-striped">
				<thead>
					<tr>
						<g:sortableColumn property="name"
							title="${message(code: 'school.name.label', default: 'School Name')}" />

						<g:sortableColumn property="numSemesters"
							title="${message(code: 'school.numSemesters.label', default: 'Number of Semesters')}" />

						<g:sortableColumn property="numDays"
							title="${message(code: 'school.numDays.label', default: 'Number of days')}" />

						<g:sortableColumn property="numPeriods"
							title="${message(code: 'school.numPeriods.label', default: 'Number of Periods')}" />

						<g:sortableColumn property="lunchPeriodStart"
							title="${message(code: 'school.lunchPeriodStart.label', default: 'Lunch start period')}" />

						<g:sortableColumn property="lunchPeriodEnd"
							title="${message(code: 'school.lunchPeriodEnd.label', default: 'Lunch end period')}" />

						<th>Actions</th>
					</tr>
				</thead>
				<tbody>
					<g:each in="${schoolInstanceList}" status="i" var="schoolInstance">
						<tr class="${(i % 2) == 0 ? 'even' : 'odd'}">
							<td>
								${fieldValue(bean: schoolInstance, field: "name")}
							</td>

							<td>
								${fieldValue(bean: schoolInstance, field: "numSemesters")}
							</td>

							<td>
								${fieldValue(bean: schoolInstance, field: "numDays")}
							</td>


							<td>
								${fieldValue(bean: schoolInstance, field: "numPeriods")}
							</td>

							<td>
								${fieldValue(bean: schoolInstance, field: "lunchPeriodStart")}
							</td>

							<td>
								${fieldValue(bean: schoolInstance, field: "lunchPeriodEnd")}
							</td>

							<td><g:link controller="school" action="edit"
									id="${schoolInstance.id}" class="btn btn-xs btn-warning"
									title="Edit school">
									<i class="fa fa-edit fa-lg"></i>
								</g:link> <g:link controller="school" action="delete"
									id="${schoolInstance.id}"
									class="btn btn-xs btn-danger action-btn"
									title="Remove school">
									<i class="fa fa-trash-o fa-lg"></i>
								</g:link></td>
						</tr>
					</g:each>
				</tbody>
			</table>
			<div class="pagination">
				<g:paginate total="${schoolInstanceCount ?: 0}" />
			</div>
		</div>
	</div>
</body>
</html>

grails-app/views/school/show.gsp
<%@ page import="com.administration.School" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'school.label', default: 'School')}" />
		<title><g:message code="default.show.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#show-school" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="show-school" class="content scaffold-show" role="main">
			<h1><g:message code="default.show.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<ol class="property-list school">
                                <g:if test="${schoolInstance?.name}">
                                <li class="fieldcontain">
                                    <span id="name-label" class="property-label"><g:message code="school.name.label" default="Name"/></span>
                                        <span class="property-value" aria-labelledby="name-label"><g:fieldValue bean="${schoolInstance}" field="numSemesters"/></span>
                                    
				<g:if test="${schoolInstance?.numSemesters}">
				<li class="fieldcontain">
					<span id="numSemesters-label" class="property-label"><g:message code="school.numSemesters.label" default="Num Semesters" /></span>
					
						<span class="property-value" aria-labelledby="numSemesters-label"><g:fieldValue bean="${schoolInstance}" field="numSemesters"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${schoolInstance?.numDays}">
				<li class="fieldcontain">
					<span id="numDays-label" class="property-label"><g:message code="school.numDays.label" default="Num Days" /></span>
					
						<span class="property-value" aria-labelledby="numDays-label"><g:fieldValue bean="${schoolInstance}" field="numDays"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${schoolInstance?.numPeriods}">
				<li class="fieldcontain">
					<span id="numPeriods-label" class="property-label"><g:message code="school.numPeriods.label" default="Num Periods" /></span>
					
						<span class="property-value" aria-labelledby="numPeriods-label"><g:fieldValue bean="${schoolInstance}" field="numPeriods"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${schoolInstance?.lunchPeriodStart}">
				<li class="fieldcontain">
					<span id="lunchPeriodStart-label" class="property-label"><g:message code="school.lunchPeriodStart.label" default="Lunch Period Start" /></span>
					
						<span class="property-value" aria-labelledby="lunchPeriodStart-label"><g:fieldValue bean="${schoolInstance}" field="lunchPeriodStart"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${schoolInstance?.lunchPeriodEnd}">
				<li class="fieldcontain">
					<span id="lunchPeriodEnd-label" class="property-label"><g:message code="school.lunchPeriodEnd.label" default="Lunch Period End" /></span>
					
						<span class="property-value" aria-labelledby="lunchPeriodEnd-label"><g:fieldValue bean="${schoolInstance}" field="lunchPeriodEnd"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${schoolInstance?.scheduleBlocks}">
				<li class="fieldcontain">
					<span id="scheduleBlocks-label" class="property-label"><g:message code="school.scheduleBlocks.label" default="Schedule Blocks" /></span>
					
						<g:each in="${schoolInstance.scheduleBlocks}" var="s">
						<span class="property-value" aria-labelledby="scheduleBlocks-label"><g:link controller="scheduleBlock" action="show" id="${s.id}">${s?.encodeAsHTML()}</g:link></span>
						</g:each>
					
				</li>
				</g:if>
			
			</ol>
			<g:form url="[resource:schoolInstance, action:'delete']" method="DELETE">
				<fieldset class="buttons">
					<g:link class="edit" action="edit" resource="${schoolInstance}"><g:message code="default.button.edit.label" default="Edit" /></g:link>
					<g:actionSubmit class="delete" action="delete" value="${message(code: 'default.button.delete.label', default: 'Delete')}" onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>